### PR TITLE
Add LookDevStudio Gem

### PR DESCRIPTION
**Pull request by HogJonny-AMZN**
This PR:

1. Adds the LookDevStudio content sample gem
2. Populates the Gem with Assets 
3. Activates the Gem in the ContentSamples project
4. Added levels (they are broken until fixed up)
5. Fixed up the level 'NoLookDev' (see comment below with image)
6. Fixed up the level 'BasicLookDev' with the PixarTeapot (open source, public domain).  You can enable RT reflections in this level, on the Level Component for SSR.
7. Fixed up the level 'LookDevStudio' with the Hermanubis, you can replace the subject matter with a new model and material easily to do look dev.  You can enable RT reflections in this level, on the Level Component for SSR.

### CODE REVIEW

**Comment by HogJonny-AMZN** [comment]
With the commit [b5d50f3](https://github.com/o3de/o3de-samples-project-gems/pull/6/commits/b5d50f393d04edd7465217c7f7768e0ec7e20704)

ContentSamples\Levels\LookDev\NoLookDev

image

**Comment by HogJonny-AMZN** [comment]
final lighting tweaks
image

**Comment by HogJonny-AMZN** [comment]
The BasicLookDev level with PixarTeapot.
This image has RT reflections enabled, they are disabled by default in the committed version, you must manually enable them on the Level Component for SSR.
image

**Comment by HogJonny-AMZN** [comment]
Fixed BasicLookDev light energy so that Reflection Cubemaps bake correctly
Here is cubemaps only
image

**Comment by HogJonny-AMZN** [comment]
Here is GI enabled + SSR enabled
image

**Comment by HogJonny-AMZN** [comment]
Here is GI enables + SSR enabled
image

**Comment by HogJonny-AMZN** [comment]
And here is with Hybrid SSR + RT enabled
image

**Comment by HogJonny-AMZN** [comment]
With last commit, here is the LookDevStudio level
In this image, No SSR or Rt reflections (just layered reflection probes)
image

**Comment by HogJonny-AMZN** [comment]
SSR reflection (on hardware RT)
image

**Comment by HogJonny-AMZN** [comment]
With full hybrid SSR + RT reflections
image

**Review by shawstar — APPROVED** [review]

**Review by aFinchy — APPROVED** [review]
Looks good!

**Pull request merged**
